name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-bootstrap-dht:latest
